### PR TITLE
Add ICON-LES highCCN radiation DOM02

### PR DESCRIPTION
**Pull request by observingClouds**

### CODE REVIEW

**Comment by observingClouds** [comment]
Still missing checksums:
```
4it [00:04,  1.00s/it]No checksum set for this resource
Probably no checksum for EUREC4A_ICON-LES_highCCN_DOM02_radiation_native.sou_t.001.tar yet on tape
7it [00:06,  1.18it/s]No checksum set for this resource
Probably no checksum for EUREC4A_ICON-LES_highCCN_DOM02_radiation_native.thb_t.001.tar yet on tape
12it [00:11,  1.02it/s]
```

**Comment by neumannd** [comment]
@observingClouds The service, which is responsible for the calculation of the checksum was not available for some time in December. If a file is archived and the checksum service is not available then the file file remain without checksum until it is written onto  tape. When a file is selected to be written onto tape and no checksum is available (and the file is not damaged) then  the checksum will be calculated.

**Comment by observingClouds** [comment]
Thanks for the clarification @neumannd . To be honest, I only trust the archival process and myself if I'm able to compare the checksums. It would be great if the checksums could be already calculated when a file is archived to the tape's cache. As a user I would get quick feedback if my job succeeded and wouldn't need to keep a local copy for any time longer.

**Comment by neumannd** [comment]
> It would be great if the checksums could be already calculated when a file is archived to the tape's cache.

That's the default (calculating it as soon as possible when the file is in the cache). In this case the checksum-calculation service hang / died. This happened now in December and once in October. Apart from that the checksums were calculated "as soon as possible". The checksum calculation is lower prioritized compared to some other processes -- e.g. copying file from/to the HSM cache. This means that the calculation of checksums might be delayed by a few hours when many files are archived. But, a day after the successful archival of a file, the checksum should be available.

**Comment by observingClouds** [comment]
Checksums are finally computed.

**Pull request merged**
